#JWT access token过期时间 1天
jwt.accessToken.expireTime: 86400  
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 5
    password: 1234567
    expireTime: 3600000 #单位秒
#是否开启 swagger，生产环境请关闭
swagger:
  enable: true